CREATE TABLE IF NOT EXISTS call_logs (
    id SERIAL PRIMARY KEY,
    call_id VARCHAR(100) UNIQUE NOT NULL,
    owner_name VARCHAR(100),
    phone VARCHAR(20),
    from_number VARCHAR(20),
    property_address TEXT,
    lead_source VARCHAR(100),
    agent_name VARCHAR(100),
    call_status VARCHAR(50),
    duration_seconds INT,
    interest_level VARCHAR(20),
    qualified VARCHAR(20),
    sell_timeline VARCHAR(50),
    motivation TEXT,
    objections TEXT,
    follow_up_required BOOLEAN,
    property_estimate VARCHAR(100),
    transcript TEXT,
    transcript_key_points TEXT,
    summary TEXT,
    sentiment VARCHAR(20),
    recording_url TEXT,
    analysis JSONB DEFAULT '{}'::jsonb,
    tool_calls JSONB DEFAULT '[]'::jsonb,
    start_timestamp TIMESTAMP,
    end_timestamp TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE call_logs
    ADD COLUMN IF NOT EXISTS from_number VARCHAR(20),
    ADD COLUMN IF NOT EXISTS qualified VARCHAR(20),
    ADD COLUMN IF NOT EXISTS sell_timeline VARCHAR(50),
    ADD COLUMN IF NOT EXISTS motivation TEXT,
    ADD COLUMN IF NOT EXISTS objections TEXT,
    ADD COLUMN IF NOT EXISTS follow_up_required BOOLEAN,
    ADD COLUMN IF NOT EXISTS transcript_key_points TEXT;
